/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PacGene */

#ifndef _Included_PacGene
#define _Included_PacGene
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
